name: 'Terraform check'

on:
  push:
    branches: [ "main" ]
  pull_request:  

jobs:
  terraform:
    name: 'Terraform Check'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: src/enviroments/dev

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read
      id-token: write

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7
        terraform_wrapper: false

    - name: Terraform Format
      run: terraform fmt -check    

    - name: Terraform Init
      run: terraform init

    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.50.3

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run TFLint
      run: tflint -f compact --config=${{ github.workspace }}/.tflint.hcl

#    - name: Checkov GitHub Action
#      uses: bridgecrewio/checkov-action@master
#      with:
#        # This will add both a CLI output to the console and create a results.sarif file
#        framework: terraform
##        output_format: cli,sarif
##        output_file_path: console,results.sarif
#      continue-on-error: true

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
#        hide-progress: false
#        format: 'sarif'
#        output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

#    - name: Upload Trivy scan results to GitHub Security tab
#      uses: github/codeql-action/upload-sarif@v2
#      with:
#        sarif_file: 'trivy-results.sarif'

    - name: Terraform Validate
      run: terraform validate